bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls")),
    path("", include("users.urls", namespace="users")),
    path("", include("search.urls")),
    path("", include("cart.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("update_item/", views.update_item, name="update-item"),
    path("cart/", views.cart, name="cart"),
    path("checkout/", views.checkout, name="checkout"),
    path("make_payment/", views.make_payment, name="make_payment"),
]

catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("manage_catalog/", views.manage_catalog, name="manage-catalog"),
    path("books", views.BookListView.as_view(), name="books"),
    path("book/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
    path("add_book/", views.add_book, name="add-book"),
    path("edit_book/<int:book_id>", views.edit_book, name="edit-book"),
    path("delete_book/<int:book_id>/", views.delete_book, name="delete-book"),
    path("add_author/", views.add_author, name="add-author"),
    path("authors", views.AuthorListView.as_view(), name="authors"),
    path("authors/<int:pk>", views.AuthorDetailView.as_view(), name="author-detail"),
    path("edit_author/<int:author_id>", views.edit_author, name="edit-author"),
    path("delete_author/<int:author_id>/", views.delete_author, name="delete-author"),
    path("genres/", views.genre_list, name="genre-list"),
    path("genre/<int:pk>/", views.GenreDetailView.as_view(), name="genre-details"),
    path("add_genre/", views.add_genre, name="add-genre"),
    path("edit_genre/<int:genre_id>", views.edit_genre, name="edit-genre"),
    path("delete_genre/<int:genre_id>/", views.delete_genre, name="delete-genre"),
]

users/urls.py
from django.urls import path, include
from users.views import SignUpView, login_view, manage_users, user_info

app_name = "users"

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("login/", login_view, name="login"),
    path("manage-users/", manage_users, name="manage_users"),
    path("user-info/", user_info, name="user-info")
]

catalog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from django.contrib.auth.models import Permission


class Genre(models.Model):
    name = models.CharField(max_length=100, help_text="Enter a book genre (e.g. Fantasy)")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("genre-details", args=[str(self.pk)])


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    bio = models.TextField(max_length=1000, blank=True, null=True)

    class Meta:
        ordering = ("last_name", "first_name")

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"

    def get_absolute_url(self):
        return reverse("author-detail", args=[str(self.id)])


class Book(models.Model):
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    title = models.CharField(max_length=100)
    price = models.FloatField()
    stock = models.BooleanField(default=True)
    coverpage = models.FileField(upload_to="media/coverpage/")
    description = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])

catalog/forms.py
from django import forms
from .models import Book, Author, Genre


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"  # Use all fields from the Book model
        widgets = {
            "genre": forms.CheckboxSelectMultiple(),  # Customize genre field widget
        }


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = "__all__"


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ["name"]

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.decorators import user_passes_test
from django.db.models import Q
from catalog.models import Book, Author, Genre
from .forms import BookForm, AuthorForm, GenreForm


def index(request):
    return redirect("books")


# BOOK
class BookListView(generic.ListView):
    model = Book
    paginate_by = 16

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return Book.objects.filter(
                Q(title__icontains=query)
                | Q(author__first_name__icontains=query)
                | Q(author__last_name__icontains=query)
            )
        return Book.objects.all()


class BookDetailView(generic.DetailView):
    model = Book


def user_in_book_store_staff_group(user):
    return user.groups.filter(name="Book Store Staff").exists()


@user_passes_test(user_in_book_store_staff_group)
def manage_catalog(request):
    books = Book.objects.all()
    authors = Author.objects.all()
    genres = Genre.objects.all()

    return render(
        request,
        "catalog/manage_catalog.html",
        {"books": books, "authors": authors, "genres": genres},
    )


@user_passes_test(user_in_book_store_staff_group)
def add_book(request):
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("books")
    else:
        form = BookForm()

    return render(request, "add_book.html", {"form": form})


@user_passes_test(user_in_book_store_staff_group)
def edit_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect("books")
    else:
        form = BookForm(instance=book)
    return render(request, "edit_book.html", {"form": form, "book": book})


@user_passes_test(user_in_book_store_staff_group)
def delete_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if request.method == "POST":
        book.delete()
        return redirect("books")
    return render(request, "delete_book.html", {"book": book})


def book_list(request):
    books = Book.objects.all()
    return render(request, "book_list.html", {"books": books})


# AUTHOR
class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return Author.objects.filter(
                Q(first_name__icontains=query) | Q(last_name__icontains=query)
            )
        return Author.objects.all()


class AuthorDetailView(generic.DetailView):
    model = Author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = self.get_object()
        context["book_list"] = author.book_set.all()
        return context


@user_passes_test(user_in_book_store_staff_group)
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("manage-catalog")
    else:
        form = AuthorForm()

    return render(request, "add_author.html", {"form": form})


@user_passes_test(user_in_book_store_staff_group)
def edit_author(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    if request.method == "POST":
        form = AuthorForm(request.POST, instance=author)
        if form.is_valid():
            form.save()
            return redirect("authors")
    else:
        form = AuthorForm(instance=author)

    return render(request, "edit_author.html", {"form": form, "author": author})


@user_passes_test(user_in_book_store_staff_group)
def delete_author(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    if request.method == "POST":
        author.delete()
        return redirect("authors")

    return render(request, "delete_author.html", {"author": author})


# GENRE
class GenreDetailView(generic.DetailView):
    model = Genre
    template_name = "catalog/genre_details.html"
    context_object_name = "selected_genre"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["books"] = Book.objects.filter(genre=self.object)
        return context


@user_passes_test(user_in_book_store_staff_group)
def add_genre(request):
    if request.method == "POST":
        form = GenreForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("add-genre")
    else:
        form = GenreForm()

    return render(request, "add_genre.html", {"form": form})


@user_passes_test(user_in_book_store_staff_group)
def edit_genre(request, genre_id):
    genre = get_object_or_404(Genre, id=genre_id)
    if request.method == "POST":
        form = GenreForm(request.POST, instance=genre)
        if form.is_valid():
            form.save()
            return redirect("genre-list")
    else:
        form = GenreForm(instance=genre)

    return render(request, "edit_genre.html", {"form": form, "genre": genre})


@user_passes_test(user_in_book_store_staff_group)
def delete_genre(request, genre_id):
    genre = get_object_or_404(Genre, id=genre_id)
    if request.method == "POST":
        genre.delete()
        return redirect("genre-list")

    return render(request, "delete_genre.html", {"genre": genre})


def genre_list(request):
    genres = Genre.objects.all()
    return render(request, "catalog/genre_list.html", {"genres": genres})

catalog/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Store</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
    <style>
        /* Add some padding below the navbar */
        body {
            padding-top: 15px;
        }

        /* Add a 5px padding between navbar and separator */
        .navbar {
            margin-bottom: 15px;
        }

        /* Add a separator line below the navbar */
        .navbar-separator {
            content: "";
            display: block;
            height: 1px;
            background-color: #ccc;
            margin-bottom: 10px;
        }
    </style>

    <script src="{% static 'js/cart.js' %}"></script>

    <!-- CSRF HANDLING IN JS -->
    <script type="text/javascript">
        var user = '{{request.user}}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getToken('csrftoken');
    </script>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">

            <a class="navbar-brand" href="{% url 'books' %}">Book Store</a>




            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-center" id="navbarTogglerDemo02">
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'books' %}">Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'authors' %}">Authors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'genre-list' %}">Genres</a>
                    </li>
                </ul>
            </div>
            {% if user.is_authenticated %}
            <div class="navbar-brand">
                <div class="mr-3">
                    <span>Welcome, {{ user.username }} </span>
                </div>
            </div>
            {% endif %}
            <a href="{% url 'cart' %}">
                <button class="cart-icon btn btn-custom" style="margin-right: 30px;">
                    &#128722; <span id="cart-total">{{ cartItems }}</span>
                </button>
            </a>

            {% if user.is_authenticated %}
            <div class="btn-group me-2" role="group" aria-label="User Actions">
                <a href="{% url 'logout' %}?next={{ request.path }}" class="btn btn-outline-info">Logout</a>
                {% if user.is_authenticated %}
                {% if user.is_superuser %}
                {% for group in user.groups.all %}
                {% if group.name == 'Book Store Staff' %}
                <a href="{% url 'manage-catalog' %}" class="btn btn-outline-info btn-inline"
                    style="white-space: nowrap;">
                    <span style="display: inline-block;">Manage Store</span></a>


                {% endif %}
                {% endfor %}
                {% endif %}
                {% endif %}

            </div>
            {% else %}
            <a href="{% url 'users:signup' %}?next={{ request.path }}" class="btn btn-outline-info me-2">
                SignUp
            </a>
            <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-outline-info me-2">
                Login
            </a>
            {% endif %}

            <form class="d-flex" method="GET" action="{% url 'search-results' %}">
                {% csrf_token %}
                <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-dark" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <!-- Add the separator line -->
    <div class="navbar-separator"></div>

    {% block content %}

    {% endblock %}


    {% block pagination %}
    {% if is_paginated %}
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}"
                    tabindex="-1">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
            <li class="page-item active">
                <a class="page-link" href="#">{{ num }} <span class="sr-only"></span></a>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>

    {% endif %}
    {% endblock %}

</body>


</html>

catalog/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>This is a main page of the Book Store</h1>




{% endblock %}