bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls")),
    path("", include("users.urls", namespace="users")),
    path("", include("search.urls")),
    path("", include("cart.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("update_item/", views.update_item, name="update-item"),
    path("cart/", views.cart, name="cart"),
    path("checkout/", views.checkout, name="checkout"),
    path("make_payment/", views.make_payment, name="make_payment"),
]

catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("manage_catalog/", views.manage_catalog, name="manage-catalog"),
    path("books", views.BookListView.as_view(), name="books"),
    path("book/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
    path("add_book/", views.add_book, name="add-book"),
    path("edit_book/<int:book_id>", views.edit_book, name="edit-book"),
    path("delete_book/<int:book_id>/", views.delete_book, name="delete-book"),
    path("add_author/", views.add_author, name="add-author"),
    path("authors", views.AuthorListView.as_view(), name="authors"),
    path("authors/<int:pk>", views.AuthorDetailView.as_view(), name="author-detail"),
    path("edit_author/<int:author_id>", views.edit_author, name="edit-author"),
    path("delete_author/<int:author_id>/", views.delete_author, name="delete-author"),
    path("genres/", views.genre_list, name="genre-list"),
    path("genre/<int:pk>/", views.GenreDetailView.as_view(), name="genre-details"),
    path("add_genre/", views.add_genre, name="add-genre"),
    path("edit_genre/<int:genre_id>", views.edit_genre, name="edit-genre"),
    path("delete_genre/<int:genre_id>/", views.delete_genre, name="delete-genre"),
]

users/urls.py
from django.urls import path, include
from users.views import SignUpView, login_view, manage_users, user_info

app_name = "users"

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("login/", login_view, name="login"),
    path("manage-users/", manage_users, name="manage_users"),
    path("user-info/", user_info, name="user-info")
]

catalog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from django.contrib.auth.models import Permission


class Genre(models.Model):
    name = models.CharField(max_length=100, help_text="Enter a book genre (e.g. Fantasy)")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("genre-details", args=[str(self.pk)])


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    bio = models.TextField(max_length=1000, blank=True, null=True)

    class Meta:
        ordering = ("last_name", "first_name")

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"

    def get_absolute_url(self):
        return reverse("author-detail", args=[str(self.id)])


class Book(models.Model):
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    title = models.CharField(max_length=100)
    price = models.FloatField()
    stock = models.BooleanField(default=True)
    coverpage = models.FileField(upload_to="media/coverpage/")
    description = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])

catalog/forms.py
from django import forms
from .models import Book, Author, Genre


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"  # Use all fields from the Book model
        widgets = {
            "genre": forms.CheckboxSelectMultiple(),  # Customize genre field widget
        }


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = "__all__"


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ["name"]

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.decorators import user_passes_test
from django.db.models import Q
from catalog.models import Book, Author, Genre
from .forms import BookForm, AuthorForm, GenreForm


def index(request):
    return redirect("books")


# BOOK
class BookListView(generic.ListView):
    model = Book
    paginate_by = 16

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return Book.objects.filter(
                Q(title__icontains=query)
                | Q(author__first_name__icontains=query)
                | Q(author__last_name__icontains=query)
            )
        return Book.objects.all()


class BookDetailView(generic.DetailView):
    model = Book


def user_in_book_store_staff_group(user):
    return user.groups.filter(name="Book Store Staff").exists()


@user_passes_test(user_in_book_store_staff_group)
def manage_catalog(request):
    books = Book.objects.all()
    authors = Author.objects.all()
    genres = Genre.objects.all()

    return render(
        request,
        "catalog/manage_catalog.html",
        {"books": books, "authors": authors, "genres": genres},
    )


@user_passes_test(user_in_book_store_staff_group)
def add_book(request):
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("books")
    else:
        form = BookForm()

    return render(request, "add_book.html", {"form": form})


@user_passes_test(user_in_book_store_staff_group)
def edit_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if request.method == "POST":
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect("books")
    else:
        form = BookForm(instance=book)
    return render(request, "edit_book.html", {"form": form, "book": book})


@user_passes_test(user_in_book_store_staff_group)
def delete_book(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    if request.method == "POST":
        book.delete()
        return redirect("books")
    return render(request, "delete_book.html", {"book": book})


def book_list(request):
    books = Book.objects.all()
    return render(request, "book_list.html", {"books": books})


# AUTHOR
class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return Author.objects.filter(
                Q(first_name__icontains=query) | Q(last_name__icontains=query)
            )
        return Author.objects.all()


class AuthorDetailView(generic.DetailView):
    model = Author

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = self.get_object()
        context["book_list"] = author.book_set.all()
        return context


@user_passes_test(user_in_book_store_staff_group)
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("manage-catalog")
    else:
        form = AuthorForm()

    return render(request, "add_author.html", {"form": form})


@user_passes_test(user_in_book_store_staff_group)
def edit_author(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    if request.method == "POST":
        form = AuthorForm(request.POST, instance=author)
        if form.is_valid():
            form.save()
            return redirect("authors")
    else:
        form = AuthorForm(instance=author)

    return render(request, "edit_author.html", {"form": form, "author": author})


@user_passes_test(user_in_book_store_staff_group)
def delete_author(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    if request.method == "POST":
        author.delete()
        return redirect("authors")

    return render(request, "delete_author.html", {"author": author})


# GENRE
class GenreDetailView(generic.DetailView):
    model = Genre
    template_name = "catalog/genre_details.html"
    context_object_name = "selected_genre"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["books"] = Book.objects.filter(genre=self.object)
        return context


@user_passes_test(user_in_book_store_staff_group)
def add_genre(request):
    if request.method == "POST":
        form = GenreForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("add-genre")
    else:
        form = GenreForm()

    return render(request, "add_genre.html", {"form": form})


@user_passes_test(user_in_book_store_staff_group)
def edit_genre(request, genre_id):
    genre = get_object_or_404(Genre, id=genre_id)
    if request.method == "POST":
        form = GenreForm(request.POST, instance=genre)
        if form.is_valid():
            form.save()
            return redirect("genre-list")
    else:
        form = GenreForm(instance=genre)

    return render(request, "edit_genre.html", {"form": form, "genre": genre})


@user_passes_test(user_in_book_store_staff_group)
def delete_genre(request, genre_id):
    genre = get_object_or_404(Genre, id=genre_id)
    if request.method == "POST":
        genre.delete()
        return redirect("genre-list")

    return render(request, "delete_genre.html", {"genre": genre})


def genre_list(request):
    genres = Genre.objects.all()
    return render(request, "catalog/genre_list.html", {"genres": genres})

catalog/templates/catalog/add_author.html
{% extends 'base.html' %}

{% block content %}
<h2>Add Author</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

catalog/templates/catalog/add_book.html
{% extends 'base.html' %}

{% block content %}

<h2>Add Book</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

catalog/templates/catalog/add_genre.html
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>

<a href="/manage_catalog/">Back</a>

catalog/templates/catalog/author_list.html
{% extends "base.html" %}

{% block content %}
<h1>Author List</h1>
{% if author_list %}
<ul>
    {% for author in author_list|dictsort:"last_name" %}
    <li>
        <a href="{{ author.get_absolute_url }}">{{ author.last_name }}</a>, {{ author.first_name }}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no authors to display.</p>
{% endif %}

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
{% if messages %}
    <div id="autoCloseAlert" class="alert alert-success alert-dismissible fade show" role="alert">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>

    <script>
        // Add JavaScript to close the alert after a specific duration (e.g., 5 seconds)
        setTimeout(function() {
            var autoCloseAlert = document.getElementById('autoCloseAlert');
            if (autoCloseAlert) {
                autoCloseAlert.classList.add('fade');
                setTimeout(function() {
                    autoCloseAlert.style.display = 'none';
                }, 500); // Adjust the duration (in milliseconds) as needed
            }
        }, 1500); // 5 seconds before auto-closing
    </script>
{% endif %}

{% if user.is_authenticated %}
{% for group in user.groups.all %}
{% if group.name == 'Book Store Staff' %}
<a href="{% url 'edit-book' book.id %}" type="button" class="btn btn-warning">Edit</a>
<a href="{% url 'delete-book' book.id %}" type="button" class="btn btn-danger">Delete</a>
{% endif %}
{% endfor %}
{% endif %}

<div class="book-detail-container">
    <div class="book-item">
        <img src="{{ book.coverpage.url }}" alt="{{ book.title }}" class="book-image common-image-class">
    </div>
    <div class="book-details">
        <h2>{{ book.title }}</h2>
        <strong>Genres:</strong>
        <p>
            {% for genre in book.genre.all %}
            <a href="{{ genre.get_absolute_url }}">{{ genre.name }}</a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
        <p><strong>Description:</strong> {{ book.description }}</p>
    </div>
    <div class="book-info d-flex flex-column align-items-center">
        <button id="add-to-cart-{{ book.id }}" data-product="{{ book.id }}" data-action="add"
            class="btn btn-outline-primary price-button update-cart">
            <span class="price">${{ book.price }}</span>
            <span class="cart-icon">&#128722;</span>
            <span class="tooltip">Add to cart</span>
        </button>
    </div>
</div>
<script type='text/javascript' src='{% static ' js/cart.js' %}'></script>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends 'base.html' %}
{% include 'custom_pagination.html' %}
{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
{% if messages %}
    <div id="autoCloseAlert" class="alert alert-success alert-dismissible fade show" role="alert">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>

    <script>
        // Add JavaScript to close the alert after a specific duration (e.g., 5 seconds)
        setTimeout(function() {
            var autoCloseAlert = document.getElementById('autoCloseAlert');
            if (autoCloseAlert) {
                autoCloseAlert.classList.add('fade');
                setTimeout(function() {
                    autoCloseAlert.style.display = 'none';
                }, 500); // Adjust the duration (in milliseconds) as needed
            }
        }, 1500); // 5 seconds before auto-closing
    </script>
{% endif %}

<div class="sorting-buttons">
    <a href="#" data-sort="title" class="btn btn-outline-dark btn-sm">Sort by Title</a>
    <a href="#" data-sort="author" class="btn btn-outline-dark btn-sm">Sort by Author</a> 
</div>


{% if book_list %}
<div class="book-container">
    {% for book in book_list %}
        {% if book.coverpage %}
        <div class="book-item">
            <a href="{{ book.get_absolute_url }}">
                <img src="{{ book.coverpage.url }}" alt="{{ book.title }}" class="book-image">
            </a>
            <div class="book-info">
                <h5><a href="{{ book.get_absolute_url }}" class="book-title">{{ book.title|truncatechars:14 }}</a></h5>
                <p class="book-author">{{ book.author }}</p>
                <div class="book-info d-flex flex-column align-items-center">
                    <button id="add-to-cart-{{ book.id }}" data-product="{{ book.id }}" data-action="add"
                        class="btn btn-outline-primary price-button update-cart">
                        <span class="price">${{ book.price }}</span>
                        <span class="cart-icon">&#128722;</span>
                        <span class="tooltip">Add to cart</span>
                    </button>
                </div>
                {% if not book.stock %}
                <p>Out of Stock</p>
                {% endif %}
            </div>
        </div>
        {% endif %}
    {% endfor %}
</div>
{% else %}
<p>There are no books in the store.</p>
{% endif %}

<script>
    // JavaScript to handle sorting
    document.addEventListener("DOMContentLoaded", function() {
        const sortingButtons = document.querySelectorAll(".sorting-buttons a");

        sortingButtons.forEach(button => {
            button.addEventListener("click", function(e) {
                e.preventDefault();
                const sortCriteria = this.getAttribute("data-sort");
                sortBooks(sortCriteria);
            });
        });

        function sortBooks(criteria) {
            const bookContainer = document.querySelector(".book-container");
            const bookItems = Array.from(bookContainer.querySelectorAll(".book-item"));

            bookItems.sort(function(a, b) {
                const aValue = a.querySelector(`.book-${criteria}`).textContent;
                const bValue = b.querySelector(`.book-${criteria}`).textContent;

                return aValue.localeCompare(bValue);
            });

            // Clear the container and append sorted items
            bookContainer.innerHTML = "";
            bookItems.forEach(item => bookContainer.appendChild(item));
        }
    });
</script>


{% endblock %}

catalog/templates/catalog/delete_author.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Author</h1>
<p>Are you sure you want to delete the author"{{ author.last_name }}{{ author.first_name }}"?</p>
<form method="post">
  {% csrf_token %}
  <input type="submit" value="Confirm Delete" class="btn btn-danger">
  <a href="{% url 'authors' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

catalog/templates/catalog/delete_book.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Book</title>
</head>

<body>
    <h1>Delete Book - {{ book.title }}</h1>
    <p>Are you sure you want to delete "{{ book.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
        <a href="{% url 'books' %}">Cancel</a>
    </form>
</body>

</html>

catalog/templates/catalog/delete_genre.html
<!-- delete_genre.html -->
{% extends 'base.html' %}

{% block content %}
<h1>Delete Genre</h1>
<p>Are you sure you want to delete the genre "{{ genre.name }}"?</p>
<form method="post">
  {% csrf_token %}
  <input type="submit" value="Confirm Delete" class="btn btn-danger">
  <a href="{% url 'genre-list' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

catalog/templates/catalog/edit_author.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Author</title>
</head>

<body>
    <h1>Edit Author - {{ author.last_name }}, {{ author.first_name }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
</body>

</html>

catalog/templates/catalog/edit_book.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Book</title>
</head>

<body>
    <h1>Edit Book - {{ book.title }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
</body>

</html>

catalog/templates/catalog/genre_details.html
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}
{% for group in user.groups.all %}
{% if group.name == 'Book Store Staff' %}
<a href="{% url 'edit-genre' selected_genre.id %}" type="button" class="btn btn-warning">Edit</a>
<a href="{% url 'delete-genre' selected_genre.id %}" type="button" class="btn btn-danger">Delete</a>
{% endif %}
{% endfor %}
{% endif %}

<h1>Books by Genre: {{ selected_genre.name }}</h1>

{% if books %}
<ul>
    {% for book in books %}
    <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
        ({{ book.author }})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no books in this genre.</p>
{% endif %}

{% endblock %}

catalog/templates/catalog/genre_list.html
{% extends "base.html" %}

{% block content %}
<h1>Genre List</h1>
{% if genres %}
<ul>
    {% for genre in genres %}
    <li>
        <a href="{{ genre.get_absolute_url }}">{{ genre.name }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no genres to display.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/manage_catalog.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h1>Add Books</h1>
      <a href="{% url 'add-book' %}" type="button" class="btn btn-primary">Add Book</a>
    </div>
    <div class="col-md-4">
      <h1>Add Authors</h1>
      <a href="{% url 'add-author' %}" type="button" class="btn btn-primary">Add Author</a>
    </div>
    <div class="col-md-4">
      <h1>Add Genres</h1>
      <a href="{% url 'add-genre' %}" type="button" class="btn btn-primary">Add Genre</a>
    </div>
    <div class="col-md-4">
      <h1>Manage Users</h1>
      <a href="{% url 'users:manage_users' %}" type="button" class="btn btn-primary">Manage Users</a>
    </div>
  </div>
</div>
{% endblock %}